routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Routing\Route;

Route::get('/', function () {
    return view('welcome');
})->name('admin.login');
Auth::routes();
Route::group([
    'namespace' => 'Auth'
], function(){
    Route::match(['get', 'post'], 'login', 'LoginController@login')->name('admin.post.login');

    Route::match(['get', 'post'], 'logout', 'LoginController@logout')->name('admin.logout');

    Route::post('register', 'RegisterController@create')->name('admin.register');

});

Route::group(['prefix' => 'home'], function () {
    Route::get('', 'HomeController@index')->name('home');
    Route::any('{id}/events-detail', 'events@detail')->name('events.detail');
    Route::resource('events', 'events');
    Route::resource('reports', 'reports');
    Route::resource('tickets', 'tickets');

    Route::match(['get', 'post'], '{id}/channels','ChannelsController@create')->name('channels.create');
    Route::match(['get', 'post'], '{id}/sessions','SessionsController@create')->name('sessions.create');
    Route::match(['get', 'post'], '{id}/add','SessionsController@add')->name('sessions.add');
    Route::match(['get', 'post'], '{id}/rooms','RoomsController@index')->name('rooms.index');
    Route::match(['get', 'post'], 'create','RoomsController@sendData')->name('rooms.create');
    Route::any('math','RoomsCapacity@index')->name('admin.rooms');
    Route::any('charjs','RoomsCapacity@charJS')->name('admin.charJs');
});

app/Http/Controllers/Api/V1/EventsController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\EventsModels;
use Illuminate\Support\Facades\Response;
use App\User;

class EventsController extends Controller
{
    protected $events;
    protected $user;
    public function __construct(EventsModels $event, User $user){
        $this->events = new EventsModels();
        $this->user = new User();
    }

    public function getDataSlug(Request $request, $organzer = '', $event = ''){
        $data = [
            'origanzers' => $organzer,
            'event' => $event,
        ];
        $organzer_id = $data['origanzers'];
//        dd($organzer_id);
        if($organzer_id == ''){
            return response()->json($data,array(
                'code' => 401,
            ));
        }
        $event_id    = $data['event'];
        $data = $this->events->getEventByOrganizerId(isset($organzer_id) ? $organzer_id : ' ');

        return response()->json($data, 200);
    }

    public function index(Request $request){
        $events = $this->events->allEvents();
        if(isset($events) && $events == null){
            return Response::json('Có lỗi xảy ra.', 500);
        }
        return response()->json(['events' => $events],200);
    }
}

app/Http/Controllers/events.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\EventsRequest;
use App\Http\Requests\EditEventsRequest;
use DB;
use App\Models\EventsModels;
use App\Models\event_ticketsModels;
use App\Models\Channels_Models;
use App\Models\Room_Models;
use App\Models\Session_Models;
class events extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $events;
    protected $tickets;
    protected $channels;
    protected $rooms;
    protected $session;

    public function __construct(EventsModels $event,event_ticketsModels $tickets,Channels_Models $channels,Room_Models $rooms,Session_Models $session){
        $this->events = new EventsModels();
        $this->tickets = new event_ticketsModels();
        $this->channels = new Channels_Models();
        $this->rooms = new Room_Models();
        $this->session = new Room_Models();
    }

    public function index()
    {
        $events = $this->events->getEventByOrganizerId(\Auth()->user()->id);
        $view = view('admin.dashboard.events.index');
        $view ->with('events',$events);
        return $view;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $view = view('admin.dashboard.events.create');
        return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EventsRequest $request)
    {
            $all = $request->all();
            EventsModels::create($all);
            session()->flash('success','create events success');
            return  redirect()->route('events.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        // $id = $request->id;
        $events = $this->events->getDetailEvents($id);
        $events = EventsModels::find($id);
        // dd($events);
        $view = view('admin.dashboard.events.edit');
        $view ->with('events', $events);
        return $view;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditEventsRequest $request, $id)
    {
        $events = $request->all();
        EventsModels::find($id)->update($events);
        session()->flash('success','edit events success');
        return redirect()->route('events.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function detail( Request $request )
    {
            $results = [];
            $id = $request->id;
            $event_rooms = EventsModels::with('channels','channels.rooms')->where('id',$id)->first();
            foreach ($event_rooms->channels as $key => $channels){
                foreach ($channels->rooms as $k => $rooms){
                    $results[] = [
                        'id'       => $rooms['id'],
                        'name'     => $rooms['name'],
                        'capacity' => $rooms['capacity']
                    ];
                }
            }
            session()->put('event_id', $id);
            $events_id = dump(session()->get('event_id'));
            $events = $this->events->getDetailEvents($id);
            $tickets = $this->tickets->showData($id);
            $channels = $this->channels->getEventByChannelsId($id);
            $session = Session_Models::all();
            // $session = Session_Models::with('rooms','rooms.channels.events')->where('id',$id)->first();
            // $session = $this->session->getDataByIdEvent($id);
            // dd($session);
            $session =Session_Models::paginate(5);
            $view = view('admin.dashboard.events.detail');
            $view ->with('events',$events);
            $view ->with('tickets',$tickets);
            $view ->with('channels',$channels);
            $view ->with('rooms',$results);
            $view ->with('session',$session);
            return $view;
    }
}

resources/views/admin/dashboard/events/create.blade.php
@extends('admin.dashboard.layout.dashboard')
@section('content')

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {{-- @if ($errors->any())
                                                <div class="alert alert-danger">
                                                    <ul class="list-group mt-2">
                                                        @foreach ($errors->all() as $error)
                                                            <p>{{ $error }}</p>
                                                        @endforeach
                                                    </ul>
                                                </div>
                                            @endif --}}
            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Manage Events</h1>
            </div>

            <div class="mb-3 pt-3 pb-2">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                    <h2 class="h4">Create new event</h2>
                </div>
            </div>

            <form  class="needs-validation" novalidate action="{{ route('events.store') }}" method="post">
                @csrf
                <div class="row">
                    <div class="col-12 col-lg-4 mb-3">
                        <label for="inputName">Name</label>
                        <!-- adding the class is-invalid to the input, shows the invalid feedback below -->
                        <input type="text" class="form-control is-invalid" id="inputName" name="name" placeholder="" value="">
                        @if ($errors->has('name'))
                            <li style="color:brown">{{ $errors->first('name') }}</li>
                        @endif
                        <input type="hidden" class="form-control is-invalid" id="inputName" name="organizer_id" placeholder="" value="1">
                        <div class="invalid-feedback">
                            Name is required.
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-4 mb-3">
                        <label for="inputSlug">Slug</label>
                        <input type="text" class="form-control" id="inputSlug" name="slug" placeholder="" value="">
                        @if ($errors->has('slug'))
                        <li style="color:brown">{{ $errors->first('slug') }}</li>
                        @endif
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-4 mb-3">
                        <label for="inputDate">Date</label>
                        <input type="date"
                               class="form-control"
                               id="inputDate"
                               name="date"
                               placeholder="yyyy-mm-dd"
                               value="">
                                @if ($errors->has('date'))
                                    <li style="color:brown">{{ $errors->first('date') }}</li>
                                @endif
                    </div>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary" type="submit">Save event</button>
                <a href="{{ route('events.index') }}">Cancel</a>
            </form>

        </main>
 @endsection

resources/views/admin/dashboard/events/detail.blade.php
@extends('admin.dashboard.layout.dashboard')
@section('menu')
            @foreach ( $events as $key )
                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>{{ $key->name }}</span>
                </h6>
            @endforeach

            <ul class="nav flex-column">
                <li class="nav-item"><a class="nav-link active" href="events/detail.html">Overview</a></li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Reports</span>
            </h6>
            <ul class="nav flex-column mb-2">
                <li class="nav-item"><a class="nav-link" href="{{ route('admin.rooms') }}">Room capacity</a></li>
            </ul>
        @endsection
@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
         @endif
        <div class="border-bottom mb-3 pt-3 pb-2 event-title">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                @foreach ($events as $key )
                <h1 class="h2"> {{ $key['name']}}</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                            @if(isset( $key->id))
                                <a href="{{ route('events.edit',$key->id) }}" class="btn btn-sm btn-outline-secondary">Edit event</a>
                            @endif
                    </div>
                </div>
            </div>
        <span class="h6">{{ $key['date']}}</span>
            @endforeach
        </div>

        <!-- Tickets -->
        <div id="tickets" class="mb-3 pt-3 pb-2">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                <h2 class="h4">Tickets</h2>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                        <a href="{{ route('tickets.create') }}" class="btn btn-sm btn-outline-secondary">
                            Create new ticket
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row tickets">
            @foreach ($tickets as $key)
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <h5 class="card-title">{{ $key->name }}</h5>
                            <p class="card-text">{{ $key->cost }}</p>
                            <p class="card-text">&nbsp;</p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        <!-- Sessions -->
        <div id="sessions" class="mb-3 pt-3 pb-2">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                <h2 class="h4">Sessions</h2>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                        @foreach ($events as $key )
                    <a href="{{ route('sessions.create',$key->id)}}" class="btn btn-sm btn-outline-secondary">
                            Create new session
                        </a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>

        <div class="table-responsive sessions">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Time</th>
                    <th>Type</th>
                    <th class="w-100">Title</th>
                    <th>Speaker</th>
                    <th>Channel</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ( $session as $key )
                    <tr>
                        <td class="text-nowrap">{{ $key->start }} - {{ $key->end }} </td>
                        <td> {{ $key->title }} </td>
                        <td><a href="sessions/edit.html"> {{ $key->title }} </a></td>
                        <td class="text-nowrap"> {{ $key->speaker }} </td>
                        <td class="text-nowrap"> {{ $key->room_id }} </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $session->links() }}
        </div>

        <!-- Channels -->
        <div id="channels" class="mb-3 pt-3 pb-2">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                <h2 class="h4">Channels</h2>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                        {{-- {{ dd($events) }} --}}
                        @foreach ($events as $key )
                             <a href="{{ route('channels.create',$key->id) }}" class="btn btn-sm btn-outline-secondary">
                            Create new channel
                        </a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>

        <div class="row channels">
            @foreach ($channels as $key )
            {{-- {{ dd($channels) }} --}}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                    <h5 class="card-title">{{ $key->name}}</h5>
                        <p class="card-text">3 sessions, 1 room</p>
                    </div>
                </div>
            </div>
            @endforeach
        </div>

        <!-- Rooms -->
        <div id="rooms" class="mb-3 pt-3 pb-2">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                <h2 class="h4">Rooms</h2>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                        @foreach ( $events as $key )
                        <a href="{{ route('rooms.index',$key->id) }}" class="btn btn-sm btn-outline-secondary">
                            Create new room
                        </a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>

        <div class="table-responsive rooms">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Capacity</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($rooms as $key )
                    <tr>
                        <td>{{ $key['name']}}</td>
                        <td>{{ $key['capacity']}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    </main>
@endsection

resources/views/admin/dashboard/events/edit.blade.php
@extends('admin.dashboard.layout.dashboard')

@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="border-bottom mb-3 pt-3 pb-2">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
            <h1 class="h2">{{ $events->name }}</h1>
        </div>
    </div>

    <form method="post" class="needs-validation" novalidate action="{{ route('events.update',$events->id) }}">
        @method('PATCH')
        @csrf
        <div class="row">
            <div class="col-12 col-lg-4 mb-3">
                <label for="inputName">Name</label>
                <!-- adding the class is-invalid to the input, shows the invalid feedback below -->
                <input type="text" class="form-control is-invalid" id="inputName" name="name" placeholder="" value="{{ $events->name }}">
                @if ($errors->has('name'))
                            <li style="color:brown">{{ $errors->first('name') }}</li>
                @endif
                <div class="invalid-feedback">
                    Name is required.
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-4 mb-3">
                <label for="inputSlug">Slug</label>
                <input type="text" class="form-control" name="slug" id="inputSlug" placeholder="" value="{{ $events->slug }}">
                @if ($errors->has('slug'))
                        <li style="color:brown">{{ $errors->first('slug') }}</li>
                @endif
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-4 mb-3">
                <label for="inputDate">Date</label>
                <input type="text"
                name="date"
                       class="form-control"
                       id="inputDate"
                       placeholder="yyyy-mm-dd"
                       value="{{ $events->date }}">
                        @if ($errors->has('date'))
                            <li style="color:brown">{{ $errors->first('date') }}</li>
                        @endif
            </div>
        </div>

        <hr class="mb-4">
        <button class="btn btn-primary" type="submit">Save</button>
        <a href="{{ route('events.index') }}" class="btn btn-link">Cancel</a>
    </form>

</main>
@endsection

resources/views/admin/dashboard/events/index.blade.php
@extends('admin.dashboard.layout.dashboard')
@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
         @endif
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Manage Events</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                        <a href="{{ route('events.create') }}" class="btn btn-sm btn-outline-secondary">Create new event</a>
                    </div>
                </div>
            </div>
            <div class="row events">
                 {{-- show events  --}}
                @foreach ($events as $key )
                {{-- {{ dd($events->toArray()) }} --}}
                {{-- {{ dd(Auth()->user()) }} --}}
                {{-- @if($key->organizer_id) --}}
                <div class="col-md-4">
                 <div class="card mb-4 shadow-sm">
                    <a href="{{ route('events.detail',$key->id) }}" class="btn text-left event">
                        <div class="card-body">
                            <h5 class="card-title">{{ $key->name }}</h5>
                            <p class="card-subtitle">{{ $key->date }}</p>
                            <hr>
                            <p class="card-text">3,546 registrations</p>
                        </div>
                    </a>
                </div>
                </div>
                {{-- @endif --}}
                @endforeach
                {{-- end show events --}}
            </div>
    </main>
@endsection