routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Routing\Route;

Route::get('/', function () {
    return view('welcome');
})->name('admin.login');
Auth::routes();
Route::group([
    'namespace' => 'Auth'
], function(){
    Route::match(['get', 'post'], 'login', 'LoginController@login')->name('admin.post.login');

    Route::match(['get', 'post'], 'logout', 'LoginController@logout')->name('admin.logout');

    Route::post('register', 'RegisterController@create')->name('admin.register');

});

Route::group(['prefix' => 'home'], function () {
    Route::get('', 'HomeController@index')->name('home');
    Route::any('{id}/events-detail', 'events@detail')->name('events.detail');
    Route::resource('events', 'events');
    Route::resource('reports', 'reports');
    Route::resource('tickets', 'tickets');

    Route::match(['get', 'post'], '{id}/channels','ChannelsController@create')->name('channels.create');
    Route::match(['get', 'post'], '{id}/sessions','SessionsController@create')->name('sessions.create');
    Route::match(['get', 'post'], '{id}/add','SessionsController@add')->name('sessions.add');
    Route::match(['get', 'post'], '{id}/rooms','RoomsController@index')->name('rooms.index');
    Route::match(['get', 'post'], 'create','RoomsController@sendData')->name('rooms.create');
    Route::any('math','RoomsCapacity@index')->name('admin.rooms');
    Route::any('charjs','RoomsCapacity@charJS')->name('admin.charJs');
});

resources/views/admin/dashboard/includes/header.blade.php
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{ route('home') }}">Event Platform</a>
<span class="navbar-organizer w-100">{{ Auth::user()->name}}</span>
   <ul class="navbar-nav px-3">
       <li class="nav-item text-nowrap">
           <a class="nav-link" href="{{ route('admin.logout') }}"document.getElementById('logout-form').submit();">Logout</a>
        <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
            @csrf
       </form> 
     </li> 
   </ul>
    {{-- <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{ route('admin.logout') }}">Event Platform</a> --}}
</nav>

resources/views/admin/dashboard/includes/nav.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item"><a class="nav-link active" href="{{ route('events.index') }}">Manage Events</a></li>
        </ul>
        @yield('menu')
    </div>
</nav>