routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Routing\Route;

Route::get('/', function () {
    return view('welcome');
})->name('admin.login');
Auth::routes();
Route::group([
    'namespace' => 'Auth'
], function(){
    Route::match(['get', 'post'], 'login', 'LoginController@login')->name('admin.post.login');

    Route::match(['get', 'post'], 'logout', 'LoginController@logout')->name('admin.logout');

    Route::post('register', 'RegisterController@create')->name('admin.register');

});

Route::group(['prefix' => 'home'], function () {
    Route::get('', 'HomeController@index')->name('home');
    Route::any('{id}/events-detail', 'events@detail')->name('events.detail');
    Route::resource('events', 'events');
    Route::resource('reports', 'reports');
    Route::resource('tickets', 'tickets');

    Route::match(['get', 'post'], '{id}/channels','ChannelsController@create')->name('channels.create');
    Route::match(['get', 'post'], '{id}/sessions','SessionsController@create')->name('sessions.create');
    Route::match(['get', 'post'], '{id}/add','SessionsController@add')->name('sessions.add');
    Route::match(['get', 'post'], '{id}/rooms','RoomsController@index')->name('rooms.index');
    Route::match(['get', 'post'], 'create','RoomsController@sendData')->name('rooms.create');
    Route::any('math','RoomsCapacity@index')->name('admin.rooms');
    Route::any('charjs','RoomsCapacity@charJS')->name('admin.charJs');
});

app/Http/Controllers/tickets.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\event_ticketsModels;
use App\Http\Requests\TicketsRequest;
class tickets extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $view = view('admin.dashboard.tickets.create');
        return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TicketsRequest $request)
    {
        $all = $request->all();
        if(isset($all)){
            unset($all['_token']);
        }
        if(isset($all)){
            if($all['amount'] == null){
                unset($all['amount']);
            }
            if($all['date'] == null){
                unset($all['date']);
            }
        }
        // dd($all);
        event_ticketsModels::create($all);
        session()->flash('success','create events success');
        return  redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/dashboard/tickets/create.blade.php
@extends('admin.dashboard.layout.dashboard')
@section('content')
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="border-bottom mb-3 pt-3 pb-2">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                    <h1 class="h2">{insert event name}</h1>
                </div>
                <span class="h6">{insert event date}</span>
            </div>

            <div class="mb-3 pt-3 pb-2">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                    <h2 class="h4">Create new ticket</h2>
                </div>
            </div>

            <form method="post" class="needs-validation"  action="{{ route('tickets.store') }}">
                @csrf
                <div class="row">
                    <div class="col-12 col-lg-4 mb-3">
                        <label for="inputName">Name</label>
                        <!-- adding the class is-invalid to the input, shows the invalid feedback below -->
                        <input required type="text" class="form-control is-invalid" id="inputName" name="name" placeholder="" value="">
                        @if ($errors->has('name'))
                            <li style="color:brown">{{ $errors->first('name') }}</li>
                        @endif
                        <input type="hidden" class="form-control is-invalid" id="inputName" name="event_id" placeholder="" value="1">
                        <div class="invalid-feedback">
                            Name is required.
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-4 mb-3">
                        <label for="inputCost">Cost</label>
                        <input type="number" class="form-control" id="inputCost" name="cost" placeholder="" value="0">
                        @if ($errors->has('cost'))
                            <li style="color:brown">{{ $errors->first('cost') }}</li>
                        @endif
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-4 mb-3">
                        <label for="selectSpecialValidity">Special Validity</label>
                        <select class="form-control" id="selectSpecialValidity" name="special_validity">
                            <option value="" selected>None</option>
                            <option value="amount">Limited amount</option>
                            <option value="date">Purchaseable till date</option>
                        </select>
                        @if ($errors->has('special_validity'))
                        <li style="color:brown">{{ $errors->first('special_validity') }}</li>
                    @endif
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-4 mb-3">
                        <label for="inputAmount">Maximum amount of tickets to be sold</label>
                        <input type="number" class="form-control" id="inputAmount" name="amount" placeholder="" value="">
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-4 mb-3">
                        <label for="inputValidTill">Tickets can be sold until</label>
                        <input type="text"
                               class="form-control"
                               id="inputValidTill"
                               name="date"
                               placeholder="yyyy-mm-dd HH:MM"
                               value="">
                    </div>
                </div>
                <hr class="mb-4">
                <button  class="btn btn-primary" type="submit">Save ticket</button>
                {{-- onclick="location.href = document.referrer; return false;" --}}
                <button onclick="location.href = document.referrer; return false;" class="btn btn-link" type="submit">Cancel</button>
                {{-- <a  href="{{  }}" class="btn btn-link">Cancel</a>   --}}
            </form>

        </main>
        @endsection